-- Account-centric schema family for the fixed mnab.sqlite3 database.
CREATE TABLE application_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE budgets (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)));
CREATE TABLE account_groups (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, name TEXT NOT NULL CHECK(trim(name)<>''), classification TEXT NOT NULL CHECK(classification IN ('cash','credit','loan','asset','liability')), sort_order INTEGER NOT NULL, collapsed INTEGER NOT NULL DEFAULT 0 CHECK(collapsed IN (0,1)), UNIQUE(id,budget_id), UNIQUE(budget_id,name), FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE accounts (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, group_id TEXT, name TEXT NOT NULL CHECK(trim(name)<>''), account_type TEXT NOT NULL CHECK(account_type IN ('checking','savings','cash','credit_card','loan','asset','liability')), sort_order INTEGER NOT NULL, closed INTEGER NOT NULL DEFAULT 0 CHECK(closed IN (0,1)), note TEXT, favorite INTEGER NOT NULL DEFAULT 0 CHECK(favorite IN (0,1)), created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(id,budget_id), UNIQUE(budget_id,name), FOREIGN KEY(budget_id) REFERENCES budgets(id), FOREIGN KEY(group_id,budget_id) REFERENCES account_groups(id,budget_id));
CREATE TABLE category_groups (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, name TEXT NOT NULL, sort_order INTEGER NOT NULL, hidden INTEGER NOT NULL DEFAULT 0 CHECK(hidden IN (0,1)), UNIQUE(id,budget_id), UNIQUE(budget_id,name), FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE categories (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, group_id TEXT NOT NULL, name TEXT NOT NULL, sort_order INTEGER NOT NULL, hidden INTEGER NOT NULL DEFAULT 0 CHECK(hidden IN (0,1)), archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)), UNIQUE(id,budget_id), UNIQUE(group_id,name), FOREIGN KEY(group_id,budget_id) REFERENCES category_groups(id,budget_id), FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE payees (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, name TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)), hidden INTEGER NOT NULL DEFAULT 0 CHECK(hidden IN (0,1)), default_category_id TEXT REFERENCES categories(id), last_used_category_id TEXT REFERENCES categories(id), UNIQUE(id,budget_id), UNIQUE(budget_id,name), FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE reconciliations (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, statement_date TEXT NOT NULL, ending_balance INTEGER NOT NULL, created_at TEXT NOT NULL, calculated_cleared_balance INTEGER NOT NULL DEFAULT 0, difference INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'completed' CHECK(state IN ('active','completed','potentially_invalid')), completed_at TEXT, invalidated_at TEXT, UNIQUE(id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id));
CREATE TABLE import_batches (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, source_name TEXT, created_at TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('staged','applied','discarded')), UNIQUE(id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id));
CREATE TABLE transactions (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, transaction_date TEXT NOT NULL, payee_id TEXT, payee_snapshot TEXT, category_id TEXT, memo TEXT, amount INTEGER NOT NULL, cleared_state TEXT NOT NULL CHECK(cleared_state IN ('uncleared','cleared','reconciled')), approval_state TEXT NOT NULL CHECK(approval_state IN ('unapproved','approved')), reconciliation_id TEXT, transfer_id TEXT, imported_fitid TEXT, import_batch_id TEXT, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)), voided INTEGER NOT NULL DEFAULT 0 CHECK(voided IN (0,1)), UNIQUE(id,budget_id), UNIQUE(account_id,imported_fitid), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id), FOREIGN KEY(payee_id,budget_id) REFERENCES payees(id,budget_id), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id), FOREIGN KEY(reconciliation_id,budget_id) REFERENCES reconciliations(id,budget_id), FOREIGN KEY(import_batch_id,budget_id) REFERENCES import_batches(id,budget_id));
CREATE TABLE subtransactions (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL, category_id TEXT NOT NULL, memo TEXT, amount INTEGER NOT NULL, sort_order INTEGER NOT NULL, UNIQUE(transaction_id,sort_order), FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE transfer_links (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, source_transaction_id TEXT NOT NULL UNIQUE, destination_transaction_id TEXT NOT NULL UNIQUE, CHECK(source_transaction_id <> destination_transaction_id), FOREIGN KEY(source_transaction_id,budget_id) REFERENCES transactions(id,budget_id), FOREIGN KEY(destination_transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE budget_assignments (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, category_id TEXT NOT NULL, budget_month TEXT NOT NULL, amount INTEGER NOT NULL, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(category_id,budget_month), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE targets (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, category_id TEXT NOT NULL, account_id TEXT, target_type TEXT NOT NULL CHECK(target_type IN ('balance_amount','balance_by_date','fixed_monthly_savings','refill_to_amount','upcoming_expense','credit_card_payoff_by_date')), amount INTEGER, due_date TEXT, recurrence TEXT NOT NULL DEFAULT 'none' CHECK(recurrence IN ('none','monthly','yearly')), created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(id,budget_id), CHECK((target_type='credit_card_payoff_by_date' AND account_id IS NOT NULL AND amount IS NULL AND due_date IS NOT NULL AND recurrence='none') OR (target_type='upcoming_expense' AND account_id IS NULL AND amount IS NOT NULL AND due_date IS NOT NULL) OR (target_type='balance_by_date' AND account_id IS NULL AND amount IS NOT NULL AND due_date IS NOT NULL AND recurrence='none') OR (target_type IN ('balance_amount','fixed_monthly_savings','refill_to_amount') AND account_id IS NULL AND amount IS NOT NULL AND due_date IS NULL AND recurrence='none')), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id));
CREATE TABLE scheduled_transactions (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, payee_id TEXT, category_id TEXT, start_date TEXT NOT NULL, recurrence TEXT NOT NULL CHECK(recurrence IN ('daily','weekly','every_two_weeks','monthly','yearly','custom_days')), custom_interval_days INTEGER, end_date TEXT, amount INTEGER NOT NULL, memo TEXT, sort_order INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), version INTEGER NOT NULL DEFAULT 1, UNIQUE(id,budget_id), CHECK((recurrence='custom_days' AND custom_interval_days>0) OR (recurrence<>'custom_days' AND custom_interval_days IS NULL)), CHECK(end_date IS NULL OR end_date>=start_date), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id), FOREIGN KEY(payee_id,budget_id) REFERENCES payees(id,budget_id), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE scheduled_occurrences (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, schedule_id TEXT NOT NULL, sequence INTEGER NOT NULL CHECK(sequence>=0), occurrence_date TEXT NOT NULL, amount INTEGER NOT NULL, payee_id TEXT, category_id TEXT, disposition TEXT NOT NULL DEFAULT 'pending' CHECK(disposition IN ('pending','skipped','dismissed','entered')), transaction_id TEXT, identity TEXT, UNIQUE(schedule_id,sequence), CHECK((disposition='entered' AND transaction_id IS NOT NULL) OR (disposition<>'entered' AND transaction_id IS NULL)), FOREIGN KEY(schedule_id,budget_id) REFERENCES scheduled_transactions(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id), FOREIGN KEY(payee_id,budget_id) REFERENCES payees(id,budget_id), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE import_candidates (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, batch_id TEXT NOT NULL, transaction_date TEXT NOT NULL, payee_text TEXT, memo TEXT, amount INTEGER NOT NULL, fitid TEXT, state TEXT NOT NULL CHECK(state IN ('pending','accepted','rejected','duplicate')), sort_order INTEGER NOT NULL, UNIQUE(batch_id,sort_order), FOREIGN KEY(batch_id,budget_id) REFERENCES import_batches(id,budget_id) ON DELETE CASCADE);
CREATE TABLE import_sources (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, source_identifier TEXT NOT NULL, display_name TEXT, archive_status TEXT NOT NULL DEFAULT 'active' CHECK(archive_status IN ('active','archived','archive_failed')), archive_retry_count INTEGER NOT NULL DEFAULT 0 CHECK(archive_retry_count>=0), archive_retry_at TEXT, archive_error TEXT, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(account_id,source_identifier), UNIQUE(id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id));
CREATE TABLE import_identities (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, account_id TEXT NOT NULL, transaction_id TEXT NOT NULL, source_id TEXT, source_record_id TEXT, fitid TEXT, normalized_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(transaction_id), UNIQUE(account_id,fitid), UNIQUE(account_id,source_id,source_record_id), CHECK(normalized_fingerprint<>''), CHECK(fitid IS NOT NULL OR (source_id IS NOT NULL AND source_record_id IS NOT NULL)), FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id), FOREIGN KEY(source_id,budget_id) REFERENCES import_sources(id,budget_id));
CREATE TABLE staged_import_candidates (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, batch_id TEXT NOT NULL, source_id TEXT, source_record_id TEXT, fitid TEXT, normalized_fingerprint TEXT NOT NULL, transaction_date TEXT NOT NULL, payee_text TEXT, memo TEXT, amount INTEGER NOT NULL, sort_order INTEGER NOT NULL, original_json TEXT, proposed_payee TEXT, proposed_category_id TEXT, proposed_memo TEXT, duplicate_class TEXT NOT NULL DEFAULT 'new' CHECK(duplicate_class IN ('new','possible_duplicate','exact_duplicate','possible_manual_match','invalid','ignored')), duplicate_explanation TEXT, warnings_json TEXT NOT NULL DEFAULT '[]', review_decision TEXT NOT NULL DEFAULT 'pending' CHECK(review_decision IN ('pending','accept','ignore','match_existing')), matched_transaction_id TEXT, exact_duplicate_override INTEGER NOT NULL DEFAULT 0 CHECK(exact_duplicate_override IN (0,1)), UNIQUE(batch_id,sort_order), CHECK(normalized_fingerprint<>''), FOREIGN KEY(batch_id,budget_id) REFERENCES import_batches(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(source_id,budget_id) REFERENCES import_sources(id,budget_id));
CREATE TABLE import_decisions (candidate_id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, decision TEXT NOT NULL CHECK(decision IN ('accepted','rejected','duplicate','manual_match')), transaction_id TEXT, decided_at TEXT NOT NULL, CHECK((decision IN ('accepted','manual_match') AND transaction_id IS NOT NULL) OR (decision IN ('rejected','duplicate') AND transaction_id IS NULL)), FOREIGN KEY(candidate_id) REFERENCES staged_import_candidates(id) ON DELETE CASCADE, FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE import_manual_matches (candidate_id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL UNIQUE, matched_at TEXT NOT NULL, FOREIGN KEY(candidate_id) REFERENCES staged_import_candidates(id) ON DELETE CASCADE, FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE change_log (id INTEGER PRIMARY KEY AUTOINCREMENT, budget_id TEXT, entity_table TEXT NOT NULL, entity_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('insert','update','delete')), changed_at TEXT NOT NULL, correlation_id TEXT NOT NULL, FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE reconciliation_transactions (reconciliation_id TEXT NOT NULL, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL, included_at TEXT NOT NULL, PRIMARY KEY(reconciliation_id, transaction_id), FOREIGN KEY(reconciliation_id,budget_id) REFERENCES reconciliations(id,budget_id), FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE reconciliation_change_log (id INTEGER PRIMARY KEY AUTOINCREMENT, reconciliation_id TEXT NOT NULL, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('update','delete')), before_snapshot TEXT NOT NULL, after_snapshot TEXT, changed_at TEXT NOT NULL, FOREIGN KEY(reconciliation_id,budget_id) REFERENCES reconciliations(id,budget_id));
CREATE TABLE credit_card_payment_categories (account_id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, category_id TEXT NOT NULL, UNIQUE(category_id), UNIQUE(account_id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE import_batch_workflow (batch_id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('selected','parsed_staged','awaiting_review','applied','archive_pending','archived','failed')), source_path TEXT, source_checksum TEXT, source_account_json TEXT, archive_path TEXT, archive_error TEXT, failure_context TEXT, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, FOREIGN KEY(batch_id,budget_id) REFERENCES import_batches(id,budget_id) ON DELETE CASCADE);
CREATE TABLE csv_mapping_presets (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, name TEXT NOT NULL, source_signature TEXT NOT NULL, mapping_json TEXT NOT NULL, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(budget_id,source_signature), FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE TABLE operation_failures (id TEXT PRIMARY KEY, budget_id TEXT, operation TEXT NOT NULL, summary TEXT NOT NULL, detail TEXT, occurred_at TEXT NOT NULL, dismissed_at TEXT, FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE INDEX idx_accounts_budget_order_v4 ON accounts(budget_id,sort_order,id);
CREATE INDEX idx_categories_group_order ON categories(group_id,sort_order);
CREATE INDEX idx_transactions_register ON transactions(account_id,transaction_date,id);
CREATE INDEX idx_transactions_budget_report ON transactions(budget_id,transaction_date,category_id);
CREATE INDEX idx_import_candidates_lookup ON import_candidates(batch_id,state,sort_order);
CREATE INDEX idx_change_log_budget_time ON change_log(budget_id,changed_at);
CREATE INDEX idx_reconciliation_account_date ON reconciliations(account_id,statement_date);
CREATE INDEX idx_reconciliation_transactions_transaction ON reconciliation_transactions(transaction_id);
CREATE INDEX idx_transactions_register_page ON transactions(account_id,archived,transaction_date DESC,id DESC);
CREATE INDEX idx_transactions_inbox_source ON transactions(account_id,approval_state,import_batch_id,transaction_date,id);
CREATE INDEX idx_transactions_month_category ON transactions(budget_id,transaction_date,category_id,archived);
CREATE INDEX idx_assignments_month_category ON budget_assignments(budget_id,budget_month,category_id);
CREATE INDEX idx_reconciliation_lookup_v4 ON reconciliation_transactions(reconciliation_id,transaction_id);
CREATE INDEX idx_import_identity_fitid ON import_identities(account_id,fitid) WHERE fitid IS NOT NULL;
CREATE INDEX idx_import_identity_fingerprint ON import_identities(account_id,normalized_fingerprint);
CREATE INDEX idx_staged_import_fingerprint ON staged_import_candidates(budget_id,normalized_fingerprint);
CREATE INDEX idx_staged_import_source ON staged_import_candidates(source_id,source_record_id);
CREATE INDEX idx_schedule_occurrence_lookup ON scheduled_occurrences(schedule_id,disposition,occurrence_date,sequence);
CREATE INDEX idx_import_workflow_state ON import_batch_workflow(budget_id,state,modified_at);
CREATE INDEX idx_operation_failures_inbox ON operation_failures(budget_id, dismissed_at, occurred_at);
CREATE INDEX idx_transactions_budget_register_page ON transactions(budget_id, archived, transaction_date DESC, id DESC);
CREATE INDEX idx_transactions_budget_report_v7 ON transactions(budget_id, archived, voided, transaction_date, account_id, category_id);
CREATE INDEX idx_reconciliations_budget_date ON reconciliations(budget_id, statement_date DESC, id DESC);
CREATE INDEX idx_scheduled_occurrences_inbox ON scheduled_occurrences(budget_id, disposition, occurrence_date, sequence);
CREATE INDEX idx_staged_candidates_batch_review ON staged_import_candidates(batch_id, review_decision, sort_order);
CREATE INDEX idx_change_log_report_revision ON change_log(budget_id, entity_table, id DESC);
CREATE UNIQUE INDEX idx_scheduled_occurrences_identity ON scheduled_occurrences(schedule_id, identity);

-- Canonical persistence names used by the storage boundary.  A few older aggregate tables above
-- remain intentionally available while callers migrate to these narrower records.
CREATE TABLE category_goals (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, category_id TEXT NOT NULL UNIQUE, account_id TEXT, goal_type TEXT NOT NULL CHECK(goal_type IN ('balance','balance_by_date','monthly','refill','expense','credit_card_payoff')), amount INTEGER, due_date TEXT, created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(id,budget_id), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id), FOREIGN KEY(account_id,budget_id) REFERENCES accounts(id,budget_id));
CREATE TABLE merchant_rules (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, pattern TEXT NOT NULL CHECK(trim(pattern)<>''), match_type TEXT NOT NULL CHECK(match_type IN ('exact','contains','prefix','regex')), payee_id TEXT, category_id TEXT, priority INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), created_at TEXT NOT NULL, modified_at TEXT NOT NULL, UNIQUE(id,budget_id), FOREIGN KEY(budget_id) REFERENCES budgets(id), FOREIGN KEY(payee_id,budget_id) REFERENCES payees(id,budget_id), FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE transaction_splits (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL, category_id TEXT NOT NULL, memo TEXT, amount INTEGER NOT NULL, sort_order INTEGER NOT NULL, UNIQUE(transaction_id,sort_order), FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id) ON DELETE CASCADE, FOREIGN KEY(category_id,budget_id) REFERENCES categories(id,budget_id));
CREATE TABLE transfers (id TEXT PRIMARY KEY, budget_id TEXT NOT NULL, source_transaction_id TEXT NOT NULL UNIQUE, destination_transaction_id TEXT NOT NULL UNIQUE, CHECK(source_transaction_id<>destination_transaction_id), UNIQUE(id,budget_id), FOREIGN KEY(source_transaction_id,budget_id) REFERENCES transactions(id,budget_id), FOREIGN KEY(destination_transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE reconciliation_changes (id INTEGER PRIMARY KEY AUTOINCREMENT, reconciliation_id TEXT NOT NULL, budget_id TEXT NOT NULL, transaction_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('insert','update','delete')), before_snapshot TEXT, after_snapshot TEXT, changed_at TEXT NOT NULL, FOREIGN KEY(reconciliation_id,budget_id) REFERENCES reconciliations(id,budget_id), FOREIGN KEY(transaction_id,budget_id) REFERENCES transactions(id,budget_id));
CREATE TABLE application_failures (id TEXT PRIMARY KEY, budget_id TEXT, operation TEXT NOT NULL CHECK(trim(operation)<>''), summary TEXT NOT NULL CHECK(trim(summary)<>''), detail TEXT, occurred_at TEXT NOT NULL, dismissed_at TEXT, FOREIGN KEY(budget_id) REFERENCES budgets(id));
CREATE INDEX idx_account_groups_order ON account_groups(budget_id,sort_order,id);
CREATE INDEX idx_accounts_group_order ON accounts(budget_id,group_id,sort_order,id);
CREATE INDEX idx_transactions_stable_register ON transactions(account_id,archived,transaction_date DESC,created_at DESC,id DESC);
CREATE INDEX idx_transactions_all_register ON transactions(budget_id,archived,transaction_date DESC,created_at DESC,id DESC);
CREATE INDEX idx_merchant_rules_lookup ON merchant_rules(budget_id,enabled,match_type,pattern,priority DESC,id);
CREATE INDEX idx_import_identity_dedup ON import_identities(account_id,normalized_fingerprint,created_at);

CREATE TRIGGER category_goals_budget_guard_insert BEFORE INSERT ON category_goals BEGIN
  SELECT CASE WHEN (SELECT budget_id FROM categories WHERE id=NEW.category_id)<>NEW.budget_id OR
    (NEW.account_id IS NOT NULL AND (SELECT budget_id FROM accounts WHERE id=NEW.account_id)<>NEW.budget_id)
    THEN RAISE(ABORT,'category goal budget mismatch') END;
END;
CREATE TRIGGER category_goals_budget_guard_update BEFORE UPDATE ON category_goals BEGIN
  SELECT CASE WHEN (SELECT budget_id FROM categories WHERE id=NEW.category_id)<>NEW.budget_id OR
    (NEW.account_id IS NOT NULL AND (SELECT budget_id FROM accounts WHERE id=NEW.account_id)<>NEW.budget_id)
    THEN RAISE(ABORT,'category goal budget mismatch') END;
END;
